targets:
  $default: 
    builders: 
      sqflite_migration|migrationDataBuilder:
        enabled: true
        generate_for:
          exclude: ['**.migration.dart']
      sqflite_migration|migrationFunctionBuilder:
        enabled: true
        generate_for:
          exclude: ['**.migration.dart']
builders:
  migrationFunctionBuilder:
    import: "package:sqflite_migration/builder.dart"
    builder_factories: ["migrationFunctionBuilder"]
    build_extensions: {".dart": ["generated/migration_function.dart"]}
    auto_apply: root_package
    build_to: source
    runs_before: []
  migrationDataBuilder:
    import: "package:sqflite_migration/builder.dart"
    builder_factories: ["migrationDataBuilder"]
    build_extensions: {".dart": [".empty.dart"]}
    auto_apply: root_package
    runs_before: [sqflite_migration|migrationFunctionBuilder]