name: sqflite_auto_migration
description: Use source_gen and build_runner to auto generate migration function for sqlite by using override migration class and annotated with version number
version: 1.0.2
author: Goxiaoy <xy1996mail@gmail.com>
homepage: https://github.com/Goxiaoy/sqflite_auto_migration

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  sqflite: ^1.1.6
  mustache4dart: '^3.0.0-dev.0.0'

dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0
