name: sqflite_auto_migration
description: auto generate migration script for sqflite
version: 0.0.1
author: Goxiaoy <xy1996mail@gmail.com>
homepage: https://github.com/Goxiaoy/sqflite_auto_migration

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  sqflite: ^1.1.6
  mustache4dart: any

dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0
